//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "FaceDetectionCore.hh"

// constructor
FaceDetectionCore::FaceDetectionCore()
{
	std::cout << "constructor FaceDetectionCore\n";
}

void FaceDetectionCore::addParam(const string& inifile)
{
    std::ifstream parameterfile;

    if (!param->searchFile(inifile, parameterfile)) {
        cerr << "The filename " << inifile << "is not found" << endl;
        return;
    }

    param->addFile(parameterfile);
}

void FaceDetectionCore::setPersonInfo(const std::vector <CommPerception::CommPersonInf> &person_info)
{
    _person_info.setPersons(person_info);
}

CommPerception::CommPersonDetection FaceDetectionCore::getPersonInfo()
{
	return _person_info;
}



