//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "CaptureSensor.hh"
#include "ColorSegmentation.hh"

#include <iostream>

CaptureSensor::CaptureSensor(SmartACE::SmartComponent *comp) 
:	CaptureSensorCore(comp)
{
	this->rGBImagePushServiceInStatus = Smart::SMART_NODATA;
//	std::cout << "constructor CaptureSensor\n";
}
CaptureSensor::~CaptureSensor() 
{
	std::cout << "destructor CaptureSensor\n";
}


void CaptureSensor::on_RGBImagePushServiceIn(const DomainVision::CommVideoImage &input)
{

	this->rGBImagePushServiceInObject = input;

	if(this->rGBImagePushServiceInObject.getDataRef().size() != 0){
		this->rGBImagePushServiceInStatus = Smart::SMART_OK;
		COMP->setVideoImage(input);
	}
}

int CaptureSensor::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	return 0;
}
int CaptureSensor::on_execute()
{
	if(this->rGBImagePushServiceInStatus != Smart::SMART_OK)
		 return 0;


//		std::vector<unsigned char> image_date;
//		image_date = this->rGBImagePushServiceInObject.getDataRef();
//		std::cout << "[CaptureSensor] on_execute data "<< this->rGBImagePushServiceInObject.getDataRef().size()<< std::endl;

	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
//	// to get the incoming data, use this methods:
//	Smart::StatusCode status;
//	DomainVision::CommVideoImage rGBImagePushServiceInObject;
//	status = this->rGBImagePushServiceInGetUpdate(rGBImagePushServiceInObject);
//	if(status != Smart::SMART_OK) {
//		std::cerr << status << std::endl;
//		// return 0;
//	} else {
//		std::cout << "received: " << rGBImagePushServiceInObject << std::endl;
//	}

//	std::cout << "Hello from CaptureSensor " << std::endl;

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int CaptureSensor::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
