//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COLORSEGMENTATIONCORE_HH
#define _COLORSEGMENTATIONCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>
#include <opencv2/opencv.hpp>
#include <DomainVision/CommRGBDImage.hh>


class ColorSegmentationCore
{
private:

public:
	DomainVision::CommVideoImage newestImage;

	ColorSegmentationCore();

	void setVideoImage(DomainVision::CommVideoImage input);
	DomainVision::CommVideoImage getVideoImage();
	cv::Mat get_Mat(const DomainVision::CommVideoImage input);
	cv::Mat Segmentation(cv::Mat img);
	cv::Point Countour(cv::Mat mask);

};
	
#endif
