//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COLORQUERYSERVICE_USER_HH
#define _COLORQUERYSERVICE_USER_HH
		
#include "ColorQueryServiceCore.hh"

class ColorQueryService : public ColorQueryServiceCore
{
protected:
public:
	ColorQueryService(Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommColorDetection, CommObjectRecognitionObjects::CommPoint2d, SmartACE::QueryId>* server);
	virtual ~ColorQueryService();
	virtual void handleQuery(const SmartACE::QueryId &id, const CommObjectRecognitionObjects::CommColorDetection& request);

	CommObjectRecognitionObjects::ROI fixROI(CommObjectRecognitionObjects::ROI input, int imagewidth, int imageheight );

};
#endif
