//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COLORSEGMENTATIONCORE_HH
#define _COLORSEGMENTATIONCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>
#include <opencv2/opencv.hpp>
#include <DomainVision/CommRGBDImage.hh>
#include <CommPerception/Color.hh>
//#include <CommObjectRecognitionObjects/Colors.hh>
#include <CommPerception/HSVSpace.hh>

class ColorSegmentationCore
{
private:

public:
	Smart::StatusCode newestImageStatus;
	DomainVision::CommVideoImage newestImage;

	ColorSegmentationCore();

	void setVideoImage(DomainVision::CommVideoImage input, Smart::StatusCode status);
	DomainVision::CommVideoImage getVideoImage();
	cv::Mat getMat(const DomainVision::CommVideoImage input);
	CommPerception::Color getColor(CommPerception::Colors color_name);
	cv::Mat segmentation(cv::Mat img, CommPerception::Color color);
	cv::Point countour(cv::Mat mask);

};
	
#endif
