//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "InstanceRecognitionCore.hh"

// constructor
InstanceRecognitionCore::InstanceRecognitionCore()
{
	std::cout << "constructor InstanceRecognitionCore\n";
}

cv::Mat InstanceRecognitionCore::getImageMat(const DomainVision::CommVideoImage input)
{

	std::cout << "[InstanceRecognitionCore] get_Mat\n";
	const unsigned char *color_frame;

	color_frame = input.get_data();

	const int w = input.get_width();
	const int h = input.get_height();

	cv::Mat image(cv::Size(w, h), CV_8UC3, (void*)input.get_data());

	return image;
}

cv::Mat InstanceRecognitionCore::getDepthImageMat(const DomainVision::CommDepthImage input)
{

	std::cout << "[InstanceRecognitionCore] get_Mat\n";
	const unsigned char *depth_frame;

	depth_frame = input.get_distances();

	const int w = input.getWidth();
	const int h = input.getHeight();

	cv::Mat image(cv::Size(w, h), CV_8UC1, (void*)input.get_distances());

	return image;
}
