//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTFACERECOGNITION_HH
#define _COMPONENTFACERECOGNITION_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "ComponentFaceRecognitionCore.hh"

#include "ComponentFaceRecognitionPortFactoryInterface.hh"
#include "ComponentFaceRecognitionExtension.hh"

// forward declarations
class ComponentFaceRecognitionPortFactoryInterface;
class ComponentFaceRecognitionExtension;

// includes for ComponentFaceRecognitionROSExtension

// includes for OpcUaBackendComponentGeneratorExtension

// includes for PlainOpcUaComponentFaceRecognitionExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <CommPerception/CommLabel.hh>
#include <CommPerception/CommLabelACE.hh>
#include <DomainVision/CommVideoImage.hh>
#include <DomainVision/CommVideoImageACE.hh>

// include tasks
// include UpcallManagers

// include input-handler(s)
// include request-handler(s)
#include "RecognitionQueryServiceAnswHandler.hh"

// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP ComponentFaceRecognition::instance()

class ComponentFaceRecognition : public ComponentFaceRecognitionCore {
private:
	static ComponentFaceRecognition *_componentFaceRecognition;
	
	// constructor
	ComponentFaceRecognition();
	
	// copy-constructor
	ComponentFaceRecognition(const ComponentFaceRecognition& cc);
	
	// destructor
	~ComponentFaceRecognition() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, ComponentFaceRecognitionPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, ComponentFaceRecognitionExtension*> componentExtensionRegistry;
	
public:
	
	// define tasks
	
	// define input-ports
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	Smart::IQueryServerPattern<DomainVision::CommVideoImage, CommPerception::CommLabel> *recognitionQueryServiceAnsw;
	Smart::QueryServerTaskTrigger<DomainVision::CommVideoImage, CommPerception::CommLabel> *recognitionQueryServiceAnswInputTaskTrigger;
	
	// define request-handlers
	RecognitionQueryServiceAnswHandler *recognitionQueryServiceAnswHandler;
	
	// definitions of ComponentFaceRecognitionROSExtension
	
	// definitions of OpcUaBackendComponentGeneratorExtension
	
	// definitions of PlainOpcUaComponentFaceRecognitionExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, ComponentFaceRecognitionPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(ComponentFaceRecognitionExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	

	// return singleton instance
	static ComponentFaceRecognition* instance()
	{
		if(_componentFaceRecognition == 0) {
			_componentFaceRecognition = new ComponentFaceRecognition();
		}
		return _componentFaceRecognition;
	}
	
	static void deleteInstance() {
		if(_componentFaceRecognition != 0) {
			delete _componentFaceRecognition;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct RecognitionQueryServiceAnsw_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} recognitionQueryServiceAnsw;
	
		//--- client port parameter ---
		
		// -- parameters for ComponentFaceRecognitionROSExtension
		
		// -- parameters for OpcUaBackendComponentGeneratorExtension
		
		// -- parameters for PlainOpcUaComponentFaceRecognitionExtension
		
	} connections;
};
#endif
