//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTFACERECOGNITIONCORE_HH
#define _COMPONENTFACERECOGNITIONCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>
#include "Facenet.h"

#include <opencv2/opencv.hpp>

using namespace perception;

class ComponentFaceRecognitionCore
{
private:
	SmartACE::SmartIniParameter* param = nullptr;
	Facenet* model;

	string graph_path;
	string database_path;
	const string default_graph_path = "/home/rosmosys/catkin_ws/src/rhome_perception/person/face_recognition/model/20180402-114759/20180402-114759.pb";
	const string default_database_path = "/home/rosmosys/catkin_ws/src/rhome_perception/person/face_recognition/data/database.csv";


public:
	ComponentFaceRecognitionCore();

	string recognize(cv::Mat image);
};
	
#endif
