//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef OBJECTLOCATION_PORTFACTORYINTERFACE_HH_
#define OBJECTLOCATION_PORTFACTORYINTERFACE_HH_

// include communication objects
#include <CommPerception/CommInfDetection.hh>
#include <CommPerception/CommInfDetectionACE.hh>
#include <CommPerception/CommObjectProperties.hh>
#include <CommPerception/CommObjectPropertiesACE.hh>
#include <DomainVision/CommRGBDImage.hh>
#include <DomainVision/CommRGBDImageACE.hh>

#include <chrono>

// include component's main class
#include "ObjectLocation.hh"

// forward declaration
class ObjectLocation;

class ObjectLocationPortFactoryInterface {
public:
	ObjectLocationPortFactoryInterface() { };
	virtual ~ObjectLocationPortFactoryInterface() { };

	virtual void initialize(ObjectLocation *component, int argc, char* argv[]) = 0;
	virtual int onStartup() = 0;

	virtual Smart::IPushClientPattern<DomainVision::CommRGBDImage> * createRGBDImagePushServiceIn() = 0;
	
	virtual Smart::IQueryServerPattern<CommPerception::CommInfDetection, CommPerception::CommObjectProperties> * createObjectQueryServiceAnsw(const std::string &serviceName) = 0;

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) = 0;
	virtual void destroy() = 0;
};

#endif /* OBJECTLOCATION_PORTFACTORYINTERFACE_HH_ */
