//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _OBJECTRECOGNITIONQUERYSERVICEANSW_USER_HH
#define _OBJECTRECOGNITIONQUERYSERVICEANSW_USER_HH
		
#include "ObjectRecognitionQueryServiceAnswCore.hh"

class ObjectRecognitionQueryServiceAnsw : public ObjectRecognitionQueryServiceAnswCore
{
private :

protected:
public:
	ObjectRecognitionQueryServiceAnsw(Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionInformation, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties, SmartACE::QueryId>* server);
	virtual ~ObjectRecognitionQueryServiceAnsw();
	virtual void handleQuery(const SmartACE::QueryId &id, const CommObjectRecognitionObjects::CommObjectRecognitionInformation& request);
	CommObjectRecognitionObjects::CommPoint2d serviceAnswer;
	void setAnswer(CommObjectRecognitionObjects::CommPoint2d input);
};
#endif
