//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _OBJECTDETECTIONCORE_HH
#define _OBJECTDETECTIONCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>
#include "armadillo.hh"
#include <opencv2/opencv.hpp>
#include <DomainVision/CommRGBDImage.hh>
#include <CommObjectRecognitionObjects/ROI.hh>
#include <CommObjectRecognitionObjects/Color.hh>

class ObjectDetectionCore
{
private:

public:
	bool evaluateColorSegmentation;
	CommObjectRecognitionObjects::CommPoint2d colorSegmentation_point;
	CommObjectRecognitionObjects::ROI roiObject;
	CommObjectRecognitionObjects::Color colorObject;

	DomainVision::CommVideoImage rGBImageObject;
	DomainVision::CommDepthImage depthImageObject;
	Smart::StatusCode rGBImageObjectStatus;
	Smart::StatusCode depthImageObjectStatus;


	ObjectDetectionCore();
	void setVideoImage(DomainVision::CommVideoImage input, Smart::StatusCode status);
	DomainVision::CommVideoImage getVideoImage();
	void setDepthImage(DomainVision::CommDepthImage input, Smart::StatusCode status);
	DomainVision::CommDepthImage getDepthImage();
//	cv::Mat getDepthMat(const DomainVision::CommDepthImage input);
	cv::Mat getImageMat(const DomainVision::CommVideoImage input);
	CommBasicObjects::CommPose3d  get3dPoint (CommObjectRecognitionObjects::CommPoint2d colorSegmentation_point, DomainVision::CommDepthImage depthImage);
};


#endif
