//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _FACEDETECTION_HH
#define _FACEDETECTION_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "FaceDetectionCore.hh"

#include "FaceDetectionPortFactoryInterface.hh"
#include "FaceDetectionExtension.hh"

// forward declarations
class FaceDetectionPortFactoryInterface;
class FaceDetectionExtension;

// includes for FaceDetectionROSExtension

// includes for PlainOpcUaFaceDetectionExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <CommPerception/CommLabel.hh>
#include <CommPerception/CommLabelACE.hh>
#include <CommPerception/CommPersonDetection.hh>
#include <CommPerception/CommPersonDetectionACE.hh>
#include <DomainVision/CommRGBDImage.hh>
#include <DomainVision/CommRGBDImageACE.hh>
#include <DomainVision/CommVideoImage.hh>
#include <DomainVision/CommVideoImageACE.hh>
#include <CommPerception/Empty.hh>
#include <CommPerception/EmptyACE.hh>

// include tasks
#include "CaptureSensor.hh"
// include UpcallManagers
#include "RGBDImagePushServiceInUpcallManager.hh"

// include input-handler
// include input-handler
#include "PersonQueryServiceAnswHandler.hh"

// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP FaceDetection::instance()

class FaceDetection : public FaceDetectionCore {
private:
	static FaceDetection *_faceDetection;
	
	// constructor
	FaceDetection();
	
	// copy-constructor
	FaceDetection(const FaceDetection& cc);
	
	// destructor
	~FaceDetection() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, FaceDetectionPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, FaceDetectionExtension*> componentExtensionRegistry;
	
public:
	
	// define tasks
	Smart::TaskTriggerSubject* captureSensorTrigger;
	CaptureSensor *captureSensor;
	
	// define input-ports
	// InputPort RGBDImagePushServiceIn
	Smart::IPushClientPattern<DomainVision::CommRGBDImage> *rGBDImagePushServiceIn;
	Smart::InputTaskTrigger<DomainVision::CommRGBDImage> *rGBDImagePushServiceInInputTaskTrigger;
	RGBDImagePushServiceInUpcallManager *rGBDImagePushServiceInUpcallManager;
	
	// define request-ports
	Smart::IQueryClientPattern<DomainVision::CommVideoImage, CommPerception::CommLabel,SmartACE::QueryId> *recognitionQueryServiceReq;
	
	// define input-handler
	
	// define output-ports
	Smart::IPushServerPattern<DomainVision::CommVideoImage> *rGBImagePushServiceOut;
	
	// define answer-ports
	Smart::IQueryServerPattern<CommPerception::Empty, CommPerception::CommPersonDetection,SmartACE::QueryId> *personQueryServiceAnsw;
	Smart::QueryServerTaskTrigger<CommPerception::Empty, CommPerception::CommPersonDetection,SmartACE::QueryId> *personQueryServiceAnswInputTaskTrigger;
	
	// define request-handlers
	PersonQueryServiceAnswHandler *personQueryServiceAnswHandler;
	
	// definitions of FaceDetectionROSExtension
	
	// definitions of PlainOpcUaFaceDetectionExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, FaceDetectionPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(FaceDetectionExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	
	Smart::StatusCode connectRGBDImagePushServiceIn(const std::string &serverName, const std::string &serviceName);
	Smart::StatusCode connectRecognitionQueryServiceReq(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static FaceDetection* instance()
	{
		if(_faceDetection == 0) {
			_faceDetection = new FaceDetection();
		}
		return _faceDetection;
	}
	
	static void deleteInstance() {
		if(_faceDetection != 0) {
			delete _faceDetection;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct CaptureSensor_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} captureSensor;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct PersonQueryServiceAnsw_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} personQueryServiceAnsw;
		struct RGBImagePushServiceOut_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} rGBImagePushServiceOut;
	
		//--- client port parameter ---
		struct RGBDImagePushServiceIn_struct {
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} rGBDImagePushServiceIn;
		struct RecognitionQueryServiceReq_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} recognitionQueryServiceReq;
		
		// -- parameters for FaceDetectionROSExtension
		
		// -- parameters for PlainOpcUaFaceDetectionExtension
		
	} connections;
};
#endif
