//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _PERSONQUERYSERVICEANSWHANDLER_CORE_HH
#define _PERSONQUERYSERVICEANSWHANDLER_CORE_HH
		
#include "aceSmartSoft.hh"

#include <CommPerception/CommPersonDetection.hh>
#include <CommPerception/Empty.hh>

// include the input interfaces (if any)

// include all interaction-observer interfaces
#include <PersonQueryServiceAnswHandlerObserverInterface.hh>

class PersonQueryServiceAnswHandlerCore 
:	public Smart::IQueryServerHandler<CommPerception::Empty, CommPerception::CommPersonDetection, SmartACE::QueryId>
,	public Smart::TaskTriggerSubject
{
private:

	virtual void updateAllCommObjects();

/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<PersonQueryServiceAnswHandlerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(PersonQueryServiceAnswHandlerObserverInterface *observer);
	void detach_interaction_observer(PersonQueryServiceAnswHandlerObserverInterface *observer);

protected:
	
public:
	PersonQueryServiceAnswHandlerCore(Smart::IQueryServerPattern<CommPerception::Empty, CommPerception::CommPersonDetection, SmartACE::QueryId>* server);
	virtual ~PersonQueryServiceAnswHandlerCore();
	//virtual void handleQuery(const SmartACE::QueryId &id, const CommPerception::Empty& request);
};
#endif
