//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENTFACEDETECTION_ACE_PORTFACTORY_HH_
#define COMPONENTFACEDETECTION_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "ComponentFaceDetectionImpl.hh"

// include the main component-definition class
#include "ComponentFaceDetectionPortFactoryInterface.hh"

class ComponentFaceDetectionAcePortFactory: public ComponentFaceDetectionPortFactoryInterface
{
private:
	ComponentFaceDetectionImpl *componentImpl;
public:
	ComponentFaceDetectionAcePortFactory();
	virtual ~ComponentFaceDetectionAcePortFactory();

	virtual void initialize(ComponentFaceDetection *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<DomainVision::CommRGBDImage> * createRGBDImagePushServiceIn() override;
	virtual Smart::IQueryClientPattern<DomainVision::CommVideoImage, CommPerception::CommLabel> * createRecognitionQueryServiceReq() override;
	
	virtual Smart::IQueryServerPattern<CommPerception::Empty, CommPerception::CommPersonDetection> * createPersonQueryServiceAnsw(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<DomainVision::CommVideoImage> * createRGBImagePushServiceOut(const std::string &serviceName) override;
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* COMPONENTFACEDETECTION_ACE_PORTFACTORY_HH_ */
