//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentFaceDetection.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentFaceDetectionAcePortFactory.hh"


// initialize static singleton pointer to zero
ComponentFaceDetection* ComponentFaceDetection::_componentFaceDetection = 0;

// constructor
ComponentFaceDetection::ComponentFaceDetection()
{
	std::cout << "constructor of ComponentFaceDetection\n";
	
	// set all pointer members to NULL
	captureSensor = NULL;
	captureSensorTrigger = NULL;
	personQueryServiceAnsw = NULL;
	personQueryServiceAnswInputTaskTrigger = NULL;
	personQueryServiceAnswHandler = NULL;
	rGBDImagePushServiceIn = NULL;
	rGBDImagePushServiceInInputTaskTrigger = NULL;
	rGBDImagePushServiceInUpcallManager = NULL;
	rGBImagePushServiceOut = NULL;
	recognitionQueryServiceReq = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentFaceDetection";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.personQueryServiceAnsw.serviceName = "PersonQueryServiceAnsw";
	connections.personQueryServiceAnsw.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImagePushServiceOut.serviceName = "RGBImagePushServiceOut";
	connections.rGBImagePushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBDImagePushServiceIn.wiringName = "RGBDImagePushServiceIn";
	connections.rGBDImagePushServiceIn.serverName = "unknown";
	connections.rGBDImagePushServiceIn.serviceName = "unknown";
	connections.rGBDImagePushServiceIn.interval = 1;
	connections.rGBDImagePushServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.recognitionQueryServiceReq.initialConnect = false;
	connections.recognitionQueryServiceReq.wiringName = "RecognitionQueryServiceReq";
	connections.recognitionQueryServiceReq.serverName = "unknown";
	connections.recognitionQueryServiceReq.serviceName = "unknown";
	connections.recognitionQueryServiceReq.interval = 1;
	connections.recognitionQueryServiceReq.roboticMiddleware = "ACE_SmartSoft";
	connections.captureSensor.minActFreq = 0.0;
	connections.captureSensor.maxActFreq = 0.0;
	// scheduling default parameters
	connections.captureSensor.scheduler = "DEFAULT";
	connections.captureSensor.priority = -1;
	connections.captureSensor.cpuAffinity = -1;
	
	// initialize members of ComponentFaceDetectionROSExtension
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaComponentFaceDetectionExtension
	
}

void ComponentFaceDetection::addPortFactory(const std::string &name, ComponentFaceDetectionPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentFaceDetection::addExtension(ComponentFaceDetectionExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentFaceDetection::getComponentImpl()
{
	return dynamic_cast<ComponentFaceDetectionAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentFaceDetection::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode ComponentFaceDetection::connectRGBDImagePushServiceIn(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = rGBDImagePushServiceIn->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->rGBDImagePushServiceIn->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	rGBDImagePushServiceIn->subscribe(connections.rGBDImagePushServiceIn.interval);
	return status;
}
Smart::StatusCode ComponentFaceDetection::connectRecognitionQueryServiceReq(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.recognitionQueryServiceReq.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = recognitionQueryServiceReq->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->recognitionQueryServiceReq->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentFaceDetection::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectRGBDImagePushServiceIn(connections.rGBDImagePushServiceIn.serverName, connections.rGBDImagePushServiceIn.serviceName);
	if(status != Smart::SMART_OK) return status;
	status = connectRecognitionQueryServiceReq(connections.recognitionQueryServiceReq.serverName, connections.recognitionQueryServiceReq.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentFaceDetection::startAllTasks() {
	// start task CaptureSensor
	if(connections.captureSensor.scheduler != "DEFAULT") {
		ACE_Sched_Params captureSensor_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.captureSensor.scheduler == "FIFO") {
			captureSensor_SchedParams.policy(ACE_SCHED_FIFO);
			captureSensor_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.captureSensor.scheduler == "RR") {
			captureSensor_SchedParams.policy(ACE_SCHED_RR);
			captureSensor_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		captureSensor->start(captureSensor_SchedParams, connections.captureSensor.cpuAffinity);
	} else {
		captureSensor->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentFaceDetection::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentFaceDetection::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "RGBDImagePushServiceIn") return rGBDImagePushServiceInInputTaskTrigger;
	
	return NULL;
}


void ComponentFaceDetection::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of ComponentFaceDetectionROSExtension
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaComponentFaceDetectionExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentFaceDetectionPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentFaceDetectionAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentFaceDetection is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		personQueryServiceAnsw = portFactoryRegistry[connections.personQueryServiceAnsw.roboticMiddleware]->createPersonQueryServiceAnsw(connections.personQueryServiceAnsw.serviceName);
		personQueryServiceAnswInputTaskTrigger = new Smart::QueryServerTaskTrigger<CommPerception::Empty, CommPerception::CommPersonDetection>(personQueryServiceAnsw);
		rGBImagePushServiceOut = portFactoryRegistry[connections.rGBImagePushServiceOut.roboticMiddleware]->createRGBImagePushServiceOut(connections.rGBImagePushServiceOut.serviceName);
		
		// create client ports
		rGBDImagePushServiceIn = portFactoryRegistry[connections.rGBDImagePushServiceIn.roboticMiddleware]->createRGBDImagePushServiceIn();
		recognitionQueryServiceReq = portFactoryRegistry[connections.recognitionQueryServiceReq.roboticMiddleware]->createRecognitionQueryServiceReq();
		
		// create InputTaskTriggers and UpcallManagers
		rGBDImagePushServiceInInputTaskTrigger = new Smart::InputTaskTrigger<DomainVision::CommRGBDImage>(rGBDImagePushServiceIn);
		rGBDImagePushServiceInUpcallManager = new RGBDImagePushServiceInUpcallManager(rGBDImagePushServiceIn);
		
		// create input-handler
		
		// create request-handlers
		personQueryServiceAnswHandler = new PersonQueryServiceAnswHandler(personQueryServiceAnsw);
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.rGBDImagePushServiceIn.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainVision::CommRGBDImage>*>(rGBDImagePushServiceIn)->add(wiringSlave, connections.rGBDImagePushServiceIn.wiringName);
		}
		if(connections.recognitionQueryServiceReq.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::QueryClient<DomainVision::CommVideoImage, CommPerception::CommLabel>*>(recognitionQueryServiceReq)->add(wiringSlave, connections.recognitionQueryServiceReq.wiringName);
		}
		
		
		
		// create Task CaptureSensor
		captureSensor = new CaptureSensor(component);
		// configure input-links
		rGBDImagePushServiceInUpcallManager->attach(captureSensor);
		// configure task-trigger (if task is configurable)
		if(connections.captureSensor.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.captureSensor.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(captureSensor);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				captureSensorTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task CaptureSensor" << std::endl;
			}
		} else if(connections.captureSensor.trigger == "DataTriggered") {
			captureSensorTrigger = getInputTaskTriggerFromString(connections.captureSensor.inPortRef);
			if(captureSensorTrigger != NULL) {
				captureSensorTrigger->attach(captureSensor, connections.captureSensor.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.captureSensor.inPortRef << " as activation source for Task CaptureSensor" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentFaceDetection::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentFaceDetection::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	rGBDImagePushServiceInUpcallManager->detach(captureSensor);
	// unlink the TaskTrigger
	if(captureSensorTrigger != NULL){
		captureSensorTrigger->detach(captureSensor);
		delete captureSensor;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete rGBDImagePushServiceInInputTaskTrigger;
	delete rGBDImagePushServiceInUpcallManager;

	// destroy client ports
	delete rGBDImagePushServiceIn;
	delete recognitionQueryServiceReq;

	// destroy server ports
	delete personQueryServiceAnsw;
	delete personQueryServiceAnswInputTaskTrigger;
	delete rGBImagePushServiceOut;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	delete personQueryServiceAnswHandler;
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of ComponentFaceDetectionROSExtension
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaComponentFaceDetectionExtension
	
}

void ComponentFaceDetection::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentFaceDetection.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentFaceDetection.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentFaceDetection.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client RGBDImagePushServiceIn
		parameter.getString("RGBDImagePushServiceIn", "serviceName", connections.rGBDImagePushServiceIn.serviceName);
		parameter.getString("RGBDImagePushServiceIn", "serverName", connections.rGBDImagePushServiceIn.serverName);
		parameter.getString("RGBDImagePushServiceIn", "wiringName", connections.rGBDImagePushServiceIn.wiringName);
		parameter.getInteger("RGBDImagePushServiceIn", "interval", connections.rGBDImagePushServiceIn.interval);
		if(parameter.checkIfParameterExists("RGBDImagePushServiceIn", "roboticMiddleware")) {
			parameter.getString("RGBDImagePushServiceIn", "roboticMiddleware", connections.rGBDImagePushServiceIn.roboticMiddleware);
		}
		// load parameters for client RecognitionQueryServiceReq
		parameter.getBoolean("RecognitionQueryServiceReq", "initialConnect", connections.recognitionQueryServiceReq.initialConnect);
		parameter.getString("RecognitionQueryServiceReq", "serviceName", connections.recognitionQueryServiceReq.serviceName);
		parameter.getString("RecognitionQueryServiceReq", "serverName", connections.recognitionQueryServiceReq.serverName);
		parameter.getString("RecognitionQueryServiceReq", "wiringName", connections.recognitionQueryServiceReq.wiringName);
		if(parameter.checkIfParameterExists("RecognitionQueryServiceReq", "roboticMiddleware")) {
			parameter.getString("RecognitionQueryServiceReq", "roboticMiddleware", connections.recognitionQueryServiceReq.roboticMiddleware);
		}
		
		// load parameters for server PersonQueryServiceAnsw
		parameter.getString("PersonQueryServiceAnsw", "serviceName", connections.personQueryServiceAnsw.serviceName);
		if(parameter.checkIfParameterExists("PersonQueryServiceAnsw", "roboticMiddleware")) {
			parameter.getString("PersonQueryServiceAnsw", "roboticMiddleware", connections.personQueryServiceAnsw.roboticMiddleware);
		}
		// load parameters for server RGBImagePushServiceOut
		parameter.getString("RGBImagePushServiceOut", "serviceName", connections.rGBImagePushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("RGBImagePushServiceOut", "roboticMiddleware")) {
			parameter.getString("RGBImagePushServiceOut", "roboticMiddleware", connections.rGBImagePushServiceOut.roboticMiddleware);
		}
		
		// load parameters for task CaptureSensor
		parameter.getDouble("CaptureSensor", "minActFreqHz", connections.captureSensor.minActFreq);
		parameter.getDouble("CaptureSensor", "maxActFreqHz", connections.captureSensor.maxActFreq);
		parameter.getString("CaptureSensor", "triggerType", connections.captureSensor.trigger);
		if(connections.captureSensor.trigger == "PeriodicTimer") {
			parameter.getDouble("CaptureSensor", "periodicActFreqHz", connections.captureSensor.periodicActFreq);
		} else if(connections.captureSensor.trigger == "DataTriggered") {
			parameter.getString("CaptureSensor", "inPortRef", connections.captureSensor.inPortRef);
			parameter.getInteger("CaptureSensor", "prescale", connections.captureSensor.prescale);
		}
		if(parameter.checkIfParameterExists("CaptureSensor", "scheduler")) {
			parameter.getString("CaptureSensor", "scheduler", connections.captureSensor.scheduler);
		}
		if(parameter.checkIfParameterExists("CaptureSensor", "priority")) {
			parameter.getInteger("CaptureSensor", "priority", connections.captureSensor.priority);
		}
		if(parameter.checkIfParameterExists("CaptureSensor", "cpuAffinity")) {
			parameter.getInteger("CaptureSensor", "cpuAffinity", connections.captureSensor.cpuAffinity);
		}
		
		// load parameters for ComponentFaceDetectionROSExtension
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaComponentFaceDetectionExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
